### ISSUE TITLE
Angular Support

### ISSUE THREAD

**Issue by Rlcolli4** [princjef/get-system-fonts#6]
Good Morning! I'm looking for a library to use in my application to load fonts locally, and I am trying to use yours but am having issues importing the function needed to run.
I am running Angular 8 and my local environment is as follows:
![localenviro](https://user-images.githubusercontent.com/12074293/73278633-1c66d080-41a9-11ea-8796-f909c5aec63e.PNG)
When I try 
`const getSystemFonts = require('get-system-fonts');`
`const files = await getSystemFonts();`
I get errors on the import, I've seen this before and tried the following types of imports as well:
`import * as fromSystemFonts from 'get-system-fonts'` and `import { getSystemFonts } from 'get-system-fonts'`
With either attempt, trying to use `getSystemFonts()` gave me an error stating "getSystemFonts has no typing" not allowing me to call the function. Thanks in advance for any insights you can give me!

**Comment by princjef** [comment]
If you're using Typescript, the types are available when the symbol is imported as a default import (i.e. `import getSystemFonts from 'get-system-fonts'`). Give that a shot and let me know if you're still having trouble.

**Comment by princjef** [comment]
Closing this for now but feel free to reopen if you don't think the question has been answered
